### ISSUE TITLE
[build] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#1]
## 📌설명
> build.gradle에 필요한 dependency 추가
querydsl 사용 위한 설정

## 🗒️Todo
- [x] spring security 관련 dependency 추가
- [x] 메일 전송을 위한 dependency 추가
- [x] 채팅 기능 구현 위한 dependency 추가
- [x] querydsl 사용 위한 설정 작성
- [x] application.properties 작성
