### ISSUE TITLE
[feat] 동행 글작성 및 삭제

### ISSUE THREAD

**Issue by yiseul-kim** [CRUDE-HI/travel-crew-server#11]
## 📌 설명
> 동행 기록 작성 및 삭제

## 🗒️ Todo
- [ ] 동행 글작성 entity 생성
- [ ] 동행 글작성 구현
- [ ] 동행 글작성 삭제 구현
