### ISSUE TITLE
[refactor] entity 및 dto 이름 변경

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#124]
### ## 📌 설명
> entity 이름 변경

## 🗒️ Todo
- [ ] entity 이름 변경
- [ ] dto 이름 변경
- [ ] 메서드 이름 변경
