### ISSUE TITLE
[refactor] 예외 처리

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#143]
## 📌 설명
> 사용자 정의 예외를 통한 예외 처리

## 🗒️ Todo
- [x] 사용자 정의 예외 class 수정
- [x] ErrorCode (http status, code, message) 수정 
- [x] global exception handler 통한 예외 일괄적으로 처리
