### ISSUE TITLE
[refactor] 동행 글, 여행 기록 전체 조회, 상세 조회 관련 코드 수정

### ISSUE THREAD

**Issue by JungwooKim9** [CRUDE-HI/travel-crew-server#154]
## 📌 설명
> 페이징 처리를 위한 동행 글, 여행 기록 전체 조회, 상세 조회 관련 코드 수정

## 🗒️ Todo
- [ ] 동행 글 전체 조회
- [ ] 여행 기록 전체 조회
- [ ] 동행 글 상세 조회
- [ ] 여행 기록 상세 조회
