### ISSUE TITLE
[feat] 여행 기록 수정

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#17]
## 📌 설명
> 여행 기록 수정 구현
## 🗒️ Todo
- [ ] 여행 기록 수정
- [ ] 여행 기록 이미지 추가
- [ ] 여행 기록 이미지 삭제
