### ISSUE TITLE
[feat] 여행 기록 좋아요 등록 및 취소

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#26]
## 📌 설명
> 여행 기록 좋아요 등록 및 취소 구현

## 🗒️ Todo
- [ ] 좋아요 entity 생성
- [ ] 좋아요 등록 구현
- [ ] 좋아요 취소 구현
