### ISSUE TITLE
[rename] 패키지 및 클래스

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#52]
## 📌 설명
> 패키지 이름 및 구조 변경
클래스명 변경

## 🗒️ Todo
- [x] 패키지 이름 및 구조 변경
- [x] 클래스 이름 변경
- [x] 사용하지 않는 메서드, 클래스, 필드 삭제
