### ISSUE TITLE
[fix] 동행 게시글 조회, 검색 수정

### ISSUE THREAD

**Issue by Me9l** [CRUDE-HI/travel-crew-server#60]
## 📌 설명
> 동행 모집글 조회 수정
> 글 등록 리펙토링

## 🗒️ Todo
- [x] CrewListRes > member객체를 String 으로 email 과 kickname 만 받도록 수정
- [x] CrewService > getCrewList 트랜잭션 처리 할 수 있도록 수정
- [x] 글 등록 api요청 수정
