### ISSUE TITLE
[feat] 동행 종료 후 리뷰 별점 작성

### ISSUE THREAD

**Issue by JungwooKim9** [CRUDE-HI/travel-crew-server#76]
## 📌 설명
> 동행 종료 후 리뷰 별점 작성

## 🗒️ Todo
- [x] 작성하지 않은 리뷰 항목이 있는지 확인
- [x] 동행 인원 정보 조회 API
- [x] 리뷰 작성
- [ ] 심박수 계산 구현 (하트 별점 1 ~ 5점 → -2, -1, 0, 1, 2)
