### ISSUE TITLE
[feat] 여행 기록 작성 및 삭제

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-server#9]
## 📌 설명
> 여행 기록 작성 및 삭제

## 🗒️ Todo
- [x] 여행 기록 entity 생성
- [x] 여행 기록에 대한 사용자 정의 예외 및 에러 코드 생성
- [x] global exception handler 통해 전역 예외 처리
- [x] querydsl config 설정 및 aws s3에 이미지 업로드 및 삭제
- [x] 여행 기록 작성 구현
- [x] 여행 기록 삭제 구현
